server:
  port: 8089
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.154.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10020/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
us:
  jwt:
    pubKeyPath: F:\usststore\rsa\rsa.pub # 公钥地址
    cookieName: US_TOKEN

