server:
  port: 8082
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/usststore
    username: root
    password: 627319
  rabbitmq:
      host: 192.168.154.128
      username: liudahai
      password: 627319
      virtual-host: /usststore
      template: #amqp的模板
        retry:
          enabled: true #重试
          initial-interval: 10000ms
          max-interval: 300000ms
          multiplier: 2
        exchange: us.item.exchange #默认交换机
      publisher-confirms: true #生产者确认

    # hikari:
      # maximum-pool-size: 30
      # minimum-idle: 10

#ribbon:
  #ConnectTimeout: 50000 # 连接超时时间(ms)
  #ReadTimeout: 50000 # 通信超时时间(ms)
  # OkToRetryOnAllOperations: true # 是否对所有操作重试
  #MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  #MaxAutoRetries: 0 # 同一实例的重试次数
#hystrix:
  #command:
    #default:
      #execution:
        #isolation:
          #thread:
            #timeoutInMillisecond: 50000 # 熔断超时时长：10000ms

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10020/eureka
  instance:
    #lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    #lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    # non-secure-port: 80
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # instance-id: ${spring.application.name}:${server.port}