server:
  port: 8087
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/usststore
    username: root
    password: 627319
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.154.128
    username: liudahai
    password: 627319
    virtual-host: /usststore
  redis:
      host: 192.168.154.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10020/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #instance-id: ${eureka.instance.ip-address}.${server.port}
    #lease-renewal-interval-in-seconds: 3
    #lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.usststore.user.pojo
