server:
  port: 8005
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false #关闭缓存
  rabbitmq:
    host: 192.168.154.128
    username: liudahai
    password: 627319
    virtual-host: /usststore
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10020/eureka
      registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 300 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #instance-id: ${spring.application.name}:${server.port}
ribbon:
  ConnectTimeout: 300000 # 连接超时时间(ms)
  ReadTimeout: 300000 # 通信超时时间(ms)
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000